In [81]:
!pip install pandas
!pip install numpy

In [82]:
import pandas as pd
import numpy as np

In [83]:
df = pd.read_csv("/content/logistics_uncleaned_5000rows.csv")

In [84]:
df

Shipment_ID  Order_ID Customer_Name Source_City Destination_City  \
0           10001     12270         Aisha     Kolkata        Hyderabad   
1           10002      5860           NaN     Kolkata              NaN   
2           10003     10390           NaN     Kolkata        Bangalore   
3           10004     10191           NaN   Hyderabad            Delhi   
4           10005     10734           NaN     Unknown        Bangalore   
...           ...       ...           ...         ...              ...   
4995        14996      9427           NaN     Unknown       Coimbatore   
4996        14997     11135          Sita     Kolkata              NaN   
4997        14998     10573           NaN   Bangalore              NaN   
4998        14999      9131          John     Kolkata       Coimbatore   
4999        15000     14900           NaN         NaN            Delhi   

     Shipment_Date Delivery_Date Transport_Mode  Weight_kg  Distance_km  \
0       2022-11-29    2022-12-10           Road       25.0        100.0   
1       2021-02-02    2022-02-01           Road       15.0        200.0   
2       2023-05-01    2022-12-24        Unknown       15.0         50.0   
3       2022-09-01    2022-09-20            Sea       30.0        200.0   
4       2022-10-29    2022-02-11            NaN        5.0        400.0   
...            ...           ...            ...        ...          ...   
4995    2021-07-06    2021-01-03           Road        0.0        400.0   
4996    2023-04-06    2023-05-04           Road        0.0        100.0   
4997    2023-01-09    2022-07-31           Rail       -5.0        -20.0   
4998    2022-07-08    2021-08-10            Sea        5.0        400.0   
4999    2022-04-04    2022-11-14            Sea        0.0        100.0   

             Vendor    Cost  Selling_Price Delivery_Status  Damage_Flag  \
0               NaN     NaN         1200.0      In Transit          0.0   
1               NaN  1500.0          300.0       Cancelled          0.0   
2           Unknown  1500.0            NaN      In Transit          NaN   
3           Unknown   800.0            0.0       Delivered          NaN   
4               DHL     0.0         1600.0             NaN          NaN   
...             ...     ...            ...             ...          ...   
4995          FedEx     0.0            0.0      In Transit          NaN   
4996  ABC Logistics   800.0          300.0       Cancelled          1.0   
4997  ABC Logistics  -100.0         1200.0      In Transit          1.0   
4998  ABC Logistics  1500.0            NaN        Returned          0.0   
4999          FedEx  1000.0          300.0        Returned          0.0   

      Delivery_Time_Days Return_Reason  Driver_Rating Vehicle_Type  \
0                    3.0    Wrong Item            0.0     Mini Van   
1                    2.0          Late            3.0          NaN   
2                    8.0          Late            NaN         Bike   
3                    1.0          Late            NaN         Bike   
4                    NaN           NaN            4.0          NaN   
...                  ...           ...            ...          ...   
4995                 2.0       Damaged            1.0          NaN   
4996                 1.0    Wrong Item            5.0         Bike   
4997                 5.0       Damaged            4.0        Truck   
4998                 5.0           NaN            2.0     Mini Van   
4999                 7.0    Wrong Item            3.0    Container   

      Fuel_Consumption_Litres  
0                        30.0  
1                        30.0  
2                        25.0  
3                        10.0  
4                        30.0  
...                       ...  
4995                    -10.0  
4996                     10.0  
4997                     15.0  
4998                     20.0  
4999                      NaN  

[5000 rows x 20 columns]

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Shipment_ID              5000 non-null   int64  
 1   Order_ID                 5000 non-null   int64  
 2   Customer_Name            3133 non-null   object 
 3   Source_City              4485 non-null   object 
 4   Destination_City         4530 non-null   object 
 5   Shipment_Date            5000 non-null   object 
 6   Delivery_Date            5000 non-null   object 
 7   Transport_Mode           4220 non-null   object 
 8   Weight_kg                4425 non-null   float64
 9   Distance_km              4375 non-null   float64
 10  Vendor                   4292 non-null   object 
 11  Cost                     4345 non-null   float64
 12  Selling_Price            4252 non-null   float64
 13  Delivery_Status          4317 non-null   object 
 14  Damage_Flag             

In [86]:
df.describe()

Shipment_ID    Order_ID    Weight_kg  Distance_km         Cost  \
count   5000.000000   5000.0000  4425.000000  4375.000000  4345.000000   
mean   12500.500000   9966.2272    12.644068   168.317714   552.036824   
std     1443.520003   2864.3132    11.412597   134.321798   539.836718   
min    10001.000000   5001.0000    -5.000000   -20.000000  -100.000000   
25%    11250.750000   7492.5000     5.000000    50.000000     0.000000   
50%    12500.500000   9974.5000    15.000000   150.000000   500.000000   
75%    13750.250000  12381.2500    25.000000   300.000000  1000.000000   
max    15000.000000  14998.0000    30.000000   400.000000  1500.000000   

       Selling_Price  Damage_Flag  Delivery_Time_Days  Driver_Rating  \
count    4252.000000  3364.000000         4600.000000    4267.000000   
mean      961.359360     0.497919            4.961739       2.501992   
std       700.452074     0.500070            3.282365       1.699034   
min         0.000000     0.000000           -1.000000       0.000000   
25%       300.000000     0.000000            2.000000       1.000000   
50%       700.000000     0.000000            5.000000       3.000000   
75%      1600.000000     1.000000            8.000000       4.000000   
max      2000.000000     1.000000           10.000000       5.000000   

       Fuel_Consumption_Litres  
count              4266.000000  
mean                 14.957806  
std                  12.777218  
min                 -10.000000  
25%                  10.000000  
50%                  15.000000  
75%                  25.000000  
max                  30.000000

In [87]:
df.shape

(5000, 20)

In [88]:
df.columns

Index(['Shipment_ID', 'Order_ID', 'Customer_Name', 'Source_City',
       'Destination_City', 'Shipment_Date', 'Delivery_Date', 'Transport_Mode',
       'Weight_kg', 'Distance_km', 'Vendor', 'Cost', 'Selling_Price',
       'Delivery_Status', 'Damage_Flag', 'Delivery_Time_Days', 'Return_Reason',
       'Driver_Rating', 'Vehicle_Type', 'Fuel_Consumption_Litres'],
      dtype='object')

In [89]:
# Identifying missing values
df.isnull().sum()

Shipment_ID                   0
Order_ID                      0
Customer_Name              1867
Source_City                 515
Destination_City            470
Shipment_Date                 0
Delivery_Date                 0
Transport_Mode              780
Weight_kg                   575
Distance_km                 625
Vendor                      708
Cost                        655
Selling_Price               748
Delivery_Status             683
Damage_Flag                1636
Delivery_Time_Days          400
Return_Reason              2507
Driver_Rating               733
Vehicle_Type                814
Fuel_Consumption_Litres     734
dtype: int64

In [90]:
# Replacing "Null","Nan","" with np.nan
df.replace(["NULL","null","nan","NaN",""],np.nan, inplace = True)

In [91]:
df["Customer_Name"].unique()

array(['Aisha', nan, 'Vikram', 'Ram', 'Sita', 'John'], dtype=object)

In [92]:
df["Customer_Name"] = df["Customer_Name"].fillna("Unknown")


In [93]:
df["Customer_Name"].unique()

array(['Aisha', 'Unknown', 'Vikram', 'Ram', 'Sita', 'John'], dtype=object)

In [94]:
df["Source_City"].unique()

array(['Kolkata', 'Hyderabad', 'Unknown', 'Chennai', 'Mumbai',
       'Bangalore', 'Pune', nan, 'Coimbatore', 'Delhi'], dtype=object)

In [95]:
df["Source_City"] = df["Source_City"].fillna("Unknown")


In [96]:
df["Source_City"].unique()

array(['Kolkata', 'Hyderabad', 'Unknown', 'Chennai', 'Mumbai',
       'Bangalore', 'Pune', 'Coimbatore', 'Delhi'], dtype=object)

In [97]:
df["Destination_City"].unique()

array(['Hyderabad', nan, 'Bangalore', 'Delhi', 'Pune', 'Unknown',
       'Mumbai', 'Coimbatore', 'Chennai', 'Kolkata'], dtype=object)

In [98]:
df["Destination_City"] = df["Destination_City"].fillna("Unknown")


In [99]:
df["Destination_City"].unique()

array(['Hyderabad', 'Unknown', 'Bangalore', 'Delhi', 'Pune', 'Mumbai',
       'Coimbatore', 'Chennai', 'Kolkata'], dtype=object)

In [100]:
df["Transport_Mode"].unique()

array(['Road', 'Unknown', 'Sea', nan, 'Rail', 'Air'], dtype=object)

In [101]:
df["Transport_Mode"] = df["Transport_Mode"].fillna("Unknown")


In [102]:
df["Transport_Mode"].unique()

array(['Road', 'Unknown', 'Sea', 'Rail', 'Air'], dtype=object)

In [103]:
df["Weight_kg"].unique()

array([25., 15., 30.,  5., nan, -5.,  0., 10., 20.])

In [104]:
# Convert negatives to absolute
df["Weight_kg"] = df["Weight_kg"].abs()

In [105]:
# Replace 0 with NaN
df["Weight_kg"] = df["Weight_kg"].replace(0, np.nan)

In [106]:
# Fill NaN with median
median_weight = df["Weight_kg"].median()
df["Weight_kg"] = df["Weight_kg"].fillna(median_weight)

In [107]:
df["Weight_kg"].unique()

array([25., 15., 30.,  5., 10., 20.])

In [108]:
df["Distance_km"].unique()

array([100., 200.,  50., 400., 300.,  nan, 150., -20.])

In [109]:
df["Distance_km"] = df["Distance_km"].abs()

In [110]:
median_distance = df["Distance_km"].median()
df["Distance_km"] = df["Distance_km"].fillna(median_distance)

In [111]:
df["Distance_km"].unique()

array([100., 200.,  50., 400., 300., 150.,  20.])

In [112]:
df["Vendor"].unique()

array([nan, 'Unknown', 'DHL', 'ABC Logistics', 'Gati', 'FedEx',
       'BlueDart'], dtype=object)

In [113]:
df["Vendor"] = df["Vendor"].fillna("Unknown")

In [114]:
df["Vendor"].unique()

array(['Unknown', 'DHL', 'ABC Logistics', 'Gati', 'FedEx', 'BlueDart'],
      dtype=object)

In [115]:
df["Cost"].unique()

array([  nan, 1500.,  800.,    0.,  500.,  200., 1000., -100.])

In [116]:
df["Cost"] = df["Cost"].abs()

df["Cost"] = df["Cost"].replace(0, np.nan)

median_cost = df["Cost"].median()
df["Cost"] = df["Cost"].fillna(median_cost)

In [117]:
df["Cost"].unique()

array([ 500., 1500.,  800.,  200., 1000.,  100.])

In [118]:
df["Selling_Price"].unique()

array([1200.,  300.,   nan,    0., 1600., 2000.,  700.])

In [119]:
df["Selling_Price"] = df["Selling_Price"].replace(0, np.nan)


df["Selling_Price"] = df["Selling_Price"].abs()

median_sp = df["Selling_Price"].median()
df["Selling_Price"] = df["Selling_Price"].fillna(median_sp)

In [120]:
df["Selling_Price"].unique()

array([1200.,  300., 1600., 2000.,  700.])

In [121]:
df["Delivery_Status"].unique()


array(['In Transit', 'Cancelled', 'Delivered', nan, 'Delayed', 'Returned',
       'Unknown'], dtype=object)

In [122]:
df["Delivery_Status"] = df["Delivery_Status"].fillna("Unknown")

In [123]:
df["Delivery_Status"].unique()


array(['In Transit', 'Cancelled', 'Delivered', 'Unknown', 'Delayed',
       'Returned'], dtype=object)

In [124]:
df["Damage_Flag"].unique()


array([ 0., nan,  1.])

In [125]:
df["Damage_Flag"] = df["Damage_Flag"].map({
    0: "No Damage",
    1: "Damaged"
})


In [126]:
df["Damage_Flag"] = df["Damage_Flag"].fillna("Unknown")

In [127]:
df["Damage_Flag"].unique()


array(['No Damage', 'Unknown', 'Damaged'], dtype=object)

In [128]:
df["Delivery_Time_Days"].unique()


array([ 3.,  2.,  8.,  1., nan,  5.,  9.,  4.,  7., 10.,  6., -1.])

In [129]:
df.loc[df["Delivery_Time_Days"] <= 0, "Delivery_Time_Days"] = np.nan

# Fill NaN with median
median_days = df["Delivery_Time_Days"].median()
df["Delivery_Time_Days"] = df["Delivery_Time_Days"].fillna(median_days)

In [130]:
df["Delivery_Time_Days"].unique()


array([ 3.,  2.,  8.,  1.,  6.,  5.,  9.,  4.,  7., 10.])

In [131]:
df["Return_Reason"].unique()


array(['Wrong Item', 'Late', nan, 'Damaged'], dtype=object)

In [132]:
df["Return_Reason"] = df["Return_Reason"].fillna("Not Returned")


In [133]:
df["Return_Reason"].unique()


array(['Wrong Item', 'Late', 'Not Returned', 'Damaged'], dtype=object)

In [134]:
df["Driver_Rating"].unique()


array([ 0.,  3., nan,  4.,  1.,  5.,  2.])

In [135]:
df["Driver_Rating"] = df["Driver_Rating"].replace(0, np.nan)


In [136]:
median_rating = df["Driver_Rating"].median()
df["Driver_Rating"] = df["Driver_Rating"].fillna(median_rating)


In [137]:
df["Driver_Rating"].unique()


array([3., 4., 1., 5., 2.])

In [138]:
df["Vehicle_Type"].unique()

array(['Mini Van', nan, 'Bike', 'Truck', 'Unknown', 'Container'],
      dtype=object)

In [139]:
df["Vehicle_Type"] = df["Vehicle_Type"].fillna("Unknown")

In [140]:
df["Vehicle_Type"].unique()

array(['Mini Van', 'Unknown', 'Bike', 'Truck', 'Container'], dtype=object)

In [141]:
df["Fuel_Consumption_Litres"].unique()

array([ 30.,  25.,  10.,  15.,  20., -10.,  nan])

In [142]:
df["Fuel_Consumption_Litres"] = df["Fuel_Consumption_Litres"].abs()


In [143]:
median_fuel = df["Fuel_Consumption_Litres"].median()
df["Fuel_Consumption_Litres"] = df["Fuel_Consumption_Litres"].fillna(median_fuel)


In [144]:
df["Fuel_Consumption_Litres"].unique()

array([30., 25., 10., 15., 20.])

In [145]:
df.isnull().sum()

Shipment_ID                0
Order_ID                   0
Customer_Name              0
Source_City                0
Destination_City           0
Shipment_Date              0
Delivery_Date              0
Transport_Mode             0
Weight_kg                  0
Distance_km                0
Vendor                     0
Cost                       0
Selling_Price              0
Delivery_Status            0
Damage_Flag                0
Delivery_Time_Days         0
Return_Reason              0
Driver_Rating              0
Vehicle_Type               0
Fuel_Consumption_Litres    0
dtype: int64

In [146]:
df.dtypes

Shipment_ID                  int64
Order_ID                     int64
Customer_Name               object
Source_City                 object
Destination_City            object
Shipment_Date               object
Delivery_Date               object
Transport_Mode              object
Weight_kg                  float64
Distance_km                float64
Vendor                      object
Cost                       float64
Selling_Price              float64
Delivery_Status             object
Damage_Flag                 object
Delivery_Time_Days         float64
Return_Reason               object
Driver_Rating              float64
Vehicle_Type                object
Fuel_Consumption_Litres    float64
dtype: object

In [147]:
df["Shipment_Date"] = pd.to_datetime(df["Shipment_Date"], errors="coerce")
df["Delivery_Date"] = pd.to_datetime(df["Delivery_Date"], errors="coerce")


In [148]:
df["Delivery_Time_Calc"] = (df["Delivery_Date"] - df["Shipment_Date"]).dt.days


In [149]:
df["Delivery_Time_Calc"].unique()

array([  11,  364, -128, ...,  714,  678, -578])

In [150]:
df["Delivery_Time_Calc"] = np.where(df["Delivery_Time_Calc"] < 0,np.nan, df["Delivery_Time_Calc"])


In [151]:
# Verified
(df["Delivery_Time_Calc"] < 0).sum()


np.int64(0)

In [152]:
df["Delivery_Time_Calc"].fillna(
    df["Delivery_Time_Calc"].median(),
    inplace=True
)


/tmp/ipython-input-2386719688.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Delivery_Time_Calc"].fillna(


In [153]:
df["Delivery_Time_Calc"].unique()

array([ 11., 364., 272.,  19., 229., 124., 299.,  16., 566., 111., 295.,
       405., 545.,  66.,  63.,  60., 307.,  65.,  82., 600., 169.,   5.,
        61., 297., 476., 561., 284., 395., 486., 463., 445., 667., 359.,
       465., 456.,  53., 248., 109., 142., 102., 457.,  49.,  58., 565.,
       343.,  37., 693., 353., 413., 319., 676., 172., 122., 741., 473.,
       388., 570., 153., 335., 189., 148., 249., 286., 110., 184.,   3.,
       631., 209., 178.,   4., 365., 517., 374., 238., 471., 162., 204.,
       522.,  62., 745., 401., 422., 459.,  50., 120.,  85., 409., 213.,
       408., 188., 271., 134., 277., 404., 154., 604., 738.,  51., 440.,
       336., 480., 618.,  15., 367.,  47., 150., 462., 407.,  90.,   8.,
        84., 118., 239., 358., 710.,  57., 472.,   6., 355., 671., 203.,
       242.,  20., 181., 257., 442., 644., 187.,  30., 699., 308., 620.,
       399., 139., 351., 661., 108., 730., 623., 165.,  29.,   1.,  79.,
       334., 232., 326., 594., 406.,  10., 180., 65

In [154]:
df.drop(columns=["Delivery_Time_Days"], inplace=True)


In [155]:
df.duplicated().sum()


np.int64(0)

In [156]:
df.to_csv("Cleaned_logistics.csv", index=False)


In [157]:
from google.colab import files
files.download("Cleaned_logistics.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>